### ISSUE TITLE
Question - Is this project right for me?

### ISSUE THREAD

**Issue by rrrrrrrrramba** [francescou/docker-compose-ui#102]
Hi all,

I would like to ask a question regarding `docker-compose-ui`. I am creating a Java library which facilitates integration tests for our company. In this library, I am given a set of `docker-compose.yml` configuration files and a set of test descriptions/tasks as input. Basically, I will be spawning services, run some tests against these services and then stopping these services.

More concrete, during the runtime, I must be able to:

- `up` and `down` `docker-compose.yml` configurations (this is easily possible via the REST API of `docker-compose-ui`)
- `up` the same `docker-compose.yml` configuration multiple times (in command line, this can be done via the `-p <unique name>` parameter) to support parallel tests
- find out which random public/host ports have been picked, as these ports are required during the execution of the tests

Is it possible to do such things with `docker-compose-ui`?

Thank you!

**Comment by francescou** [comment]
Hello @rrrrrrrrramba 
Points 1 and 3 should be straightforward using [docker-compose-ui HTTP API](https://francescou.github.io/docker-compose-ui/api.html).

Regarding the second point, in docker-compose-ui there is a tight relationship between "projects" and docker-compose.yml files, so if you need to spin up multiple instances of the composition you should create a new project and then delete it (you can do it using the HTTP API, as well. It should be similar to the "clone project" functionality).

However, since you're developing in java, I suggest you to give a look at https://www.testcontainers.org/usage/docker_compose.html

**Comment by rrrrrrrrramba** [comment]
Thank you. I already started experimenting and everything looks to be covered so far. Really great! Regarding point 2, cloning a project seems indeed the way to go, it works fine.

I will also start look into the testcontainers project. I did not know it. Thanks for the reference.
