### ISSUE TITLE
Logs with colors

### ISSUE THREAD

**Issue by zbbfufu** [francescou/docker-compose-ui#20]
Hello,
Nice project :+1: 

Should it be possible to 'prettify' logs ?
Especially ansi colors codes (https://en.wikipedia.org/wiki/ANSI_escape_code#Colors).

Here a sample nginx logs output from your log endpoint **/api/v1/logs/:id/:container/:limit**

> "2016-02-29T10:25 \u001b[0;37;1mforego     | \u001b[0mstarting nginx.1 on port 5000", 
>     "2016-02-29T10:25 \u001b[0;37;1mforego     | \u001b[0mstarting dockergen.1 on port 5100", 
>     "2016-02-29T10:25 \u001b[0;33;1mdockergen.1 | \u001b[0;31;1m2016/02/29 10:25:31 Generated '/etc/nginx/conf.d/default.conf' from 4 containers", 
>     "2016-02-29T10:25 \u001b[0m\u001b[0;33;1mdockergen.1 | \u001b[0;31;1m2016/02/29 10:25:31 Running 'nginx -s reload'", 
>     "2016-02-29T10:25 \u001b[0m\u001b[0;33;1mdockergen.1 | \u001b[0;31;1m2016/02/29 10:25:32 Watching docker events", 

Here "\u001b[0;36;1mnginx.1    | \u001b[0m" should display "nginx.1    | " in cyan (36) and bold (1).

You may use https://github.com/ralphbean/ansi2html in Python or https://github.com/rburns/ansi-to-html in Javascript.

Regards
Julien

**Comment by francescou** [comment]
Hello Julien,

thanks for the suggestion, I'll do some investigation about this, I could add this feature in the upcoming [1.0](https://github.com/francescou/docker-compose-ui/issues/14) release

**Comment by francescou** [comment]
Hello Julien,

I've just created a new branch [ansiToHtml](https://github.com/francescou/docker-compose-ui/tree/ansiToHtml) with some additions to support colored logs.

However, I am not really keen to merge this feature into master, since it requires to explicitly enable HTML rendering (it could be confusing to have rendered HTML inside logs...)

If you want, I think you can fork the repository, switch to the _ansiToHtml_ branch and 
then keep it up-to-date with  _upstream/master_

**Comment by zbbfufu** [comment]
Thanks Franceso, I'll try it :)

**Comment by francescou** [comment]
I'm closing the issue, feel free to reopen if necessary
